### ISSUE TITLE
How to Implement in java code pls help.

### ISSUE THREAD

**Issue by vimalcvs** [prathameshmm02/ThemeEngine#2]
How to Implement in java code pls help.

`
ThemeChooserDialogBuilder(this)

    // Set Title
    .setTitle(R.string.choose_theme)
    
    // Set positive button text and an OnClickListener on the button
    .setPositiveButton("OK") { position, theme ->
      // This sets staticTheme
      themeEngine.staticTheme = theme
      recreate()
    }
    
    // Set negative button text
    .setNegativeButton("Cancel")
    
    // Set neutral button text and an OnClickListener on the button
    .setNeutralButton("Default") { _, _ ->
        // This resets static theme
        themeEngine.resetTheme()
        // Recreates activity
        recreate()
    }
    
    // Set Dialog Icon
    .setIcon(R.drawable.ic_round_brush)
    
    // Create Alert Dialog
    .create()
    // Show Dialog
    .show()

`

**Comment by prathameshmm02** [comment]
Just the ThemeChooserDialog code or anything else?

**Comment by prathameshmm02** [comment]
Here's the code:
``` java

            ThemeEngine themeEngine = ThemeEngine.getInstance(this);
            new ThemeChooserDialogBuilder(this)
                    .setTitle(R.string.choose_theme)
                    .setPositiveButton("Ok", (i, theme) -> {
                        // This sets staticTheme
                        themeEngine.setStaticTheme(theme);
                        recreate();
                    })
                    // Set negative button text
                    .setNegativeButton("Cancel")

                    // Set neutral button text and an OnClickListener on the button
                    .setNeutralButton("Default", (i, theme) -> {
                        themeEngine.resetTheme();
                        recreate();
                    })
                    // Set Dialog Icon
                    .setIcon(R.drawable.ic_round_brush)
                    // Create Alert Dialog
                    .create()
                    // Show Dialog
                    .show();
        });

```
